MODEL:
  architecture:  "TSViT_single_token"
  img_res: 32
  max_seq_len: 80
  num_channels: 11
  num_features: 16
  num_classes: 12
  ignore_background: 0
  dropout: 0.
  patch_size: 2
  dim: 128
  temporal_depth: 4
  spatial_depth: 4
  heads: 4
  pool: 'cls'
  dim_head: 32
  emb_dropout: 0.
  scale_dim: 4

DATASETS:
  train:
    dataset: "PASTIS24_fold1"
    label_map:
    max_seq_len: 80
    batch_size: 16
    extra_data:
    num_workers: 4

  eval:
    dataset: "PASTIS24_fold1"
    label_map:
    max_seq_len: 80
    batch_size: 16
    extra_data:
    num_workers: 4

  test:
    dataset: "PASTIS24_fold1"
    label_map:
    max_seq_len: 80
    batch_size: 16
    extra_data:
    num_workers: 4

SOLVER:
  num_epochs: 100
  num_warmup_epochs: 5
  steps: (0, 80000)
  loss_function:  masked_cross_entropy
  class_weights:
  lr_scheduler: 'cosine'
  lr_base: 1e-3
  lr_min: 5e-6
  lr_start: 1e-8
  lr_decay: 0.97
  num_cycles: 1
  reset_lr: True   # resets lr to base value when loading pretrained model
  weight_decay: 0.000

CHECKPOINT:
  load_from_checkpoint: './PASTIS24_checkpoints/TSViT_fold1'
  partial_restore: False
  save_path: '/root/autodl-tmp/GXData_MSELoss_ignore_result_cls0_1_epoch100'
  train_metrics_steps: 250
  eval_steps: 2000
  save_steps: 20000000000
