CHECKPOINT:
  eval_steps: 2000
  load_from_checkpoint: ./PASTIS24_checkpoints/TSViT_fold1
  partial_restore: false
  save_path: models/saved_models/PASTIS24_MSEloss/TSViT_fold1
  save_steps: 20000000000
  train_metrics_steps: 250
DATASETS:
  eval:
    base_dir: /root/autodl-tmp/PASTIS24/DATA
    batch_size: 16
    bidir_input: false
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
    paths: /root/autodl-tmp/PASTIS24/DATA/fold-paths/fold_4_paths.csv
  test:
    batch_size: 16
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
  train:
    base_dir: /root/autodl-tmp/PASTIS24/DATA
    batch_size: 16
    bidir_input: false
    dataset: PASTIS24_fold1
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
    paths: /root/autodl-tmp/PASTIS24/DATA/fold-paths/folds_1_123_paths.csv
MODEL:
  architecture: TSViT_single_token
  dim: 128
  dim_head: 32
  dropout: 0.0
  emb_dropout: 0.0
  heads: 4
  ignore_background: false
  img_res: 24
  max_seq_len: 60
  num_channels: 11
  num_classes: 19
  num_features: 16
  patch_size: 2
  pool: cls
  scale_dim: 4
  spatial_depth: 4
  temporal_depth: 4
SOLVER:
  class_weights: null
  loss_function: masked_cross_entropy
  lr_base: 1e-3
  lr_decay: 0.97
  lr_min: 5e-6
  lr_scheduler: cosine
  lr_start: 1e-8
  num_cycles: 1
  num_epochs: 20
  num_warmup_epochs: 5
  reset_lr: true
  steps: (0, 80000)
  weight_decay: 0.0
local_device_ids:
- 0
- 1
