CHECKPOINT:
  eval_steps: 2000
  load_from_checkpoint: null
  machine: local
  partial_restore: false
  save_path: models/savedmodels/PASTIS24/TSViT_fold4_2
  save_steps: 20000000000
  train_metrics_steps: 250
DATASETS:
  eval:
    base_dir: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24
    batch_size: 24
    dataset: PASTIS24_fold4
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
    paths: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24/fold-paths/fold_2_paths.csv
  test:
    base_dir: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24
    batch_size: 24
    dataset: PASTIS24_fold4
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
    paths: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24/fold-paths/fold_3_paths.csv
  train:
    base_dir: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24
    batch_size: 16
    dataset: PASTIS24_fold4
    extra_data: null
    label_map: null
    max_seq_len: 60
    num_workers: 4
    paths: /media/michaeltrs/0a8a5a48-ede5-47d0-8eff-10d11350bf98/Satellite_Data/PASTIS24/fold-paths/folds_4_451_paths.csv
MODEL:
  architecture: TSViT
  dim: 128
  dim_head: 32
  dropout: 0.0
  emb_dropout: 0.0
  heads: 4
  ignore_background: false
  img_res: 24
  max_seq_len: 60
  num_channels: 11
  num_classes: 19
  num_features: 16
  patch_size: 2
  pool: cls
  scale_dim: 4
  spatial_depth: 4
  temporal_depth: 4
SOLVER:
  class_weights: null
  loss_function: masked_cross_entropy
  lr_base: 1e-3
  lr_min: 5e-6
  lr_scheduler: cosine
  lr_start: 1e-8
  num_cycles: 1
  num_epochs: 100
  num_warmup_epochs: 10
  reset_lr: true
  steps: (0, 80000)
  weight_decay: 0.0
local_device_ids:
- 0
- 1
